# Generated by Django 4.2.11 on 2024-04-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_order",
            name="hotel",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="product_order",
        ),
    ]
